### ISSUE TITLE
Internal renames on soroban-env-host

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1042]
There are a few modules renamings we should probably do for clarity in soroban-env-host:

```[tasklist]
### Tasks
- [ ] `native_contract` -> `builtin_contracts`
- [ ] `native_contract::token` -> `builtin_contracts::stellar_asset_contract`
- [ ] `native_contract::token::Token` -> `builtin_contracts::stellar_asset_contract::StellarAssetContract`
- [ ] `soroban-native-sdk-macros` -> `soroban-builtin-sdk-macros`
- [x] `ContractExecutableType` `CONTRACT_EXECUTABLE_TOKEN` -> `CONTRACT_EXECUTABLE_STELLAR_ASSET`
```

**Comment by anupsdf** [comment]
XDR changes are part of [#159](https://github.com/stellar/stellar-xdr/pull/159)

**Comment by graydon** [comment]
XDR has merged but changes haven't been taken to env yet

**Comment by graydon** [comment]
note `soroban-native-sdk-macros` is actually a crate name registered on crates.io: https://crates.io/crates/soroban-native-sdk-macros

**Comment by anupsdf** [comment]
Does this mean we [cargo yank](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank) the published old crate and publish the renamed crate?

**Comment by graydon** [comment]
I guess. Or we could just not bother with that rename. I don't feel really strongly.
