### ISSUE TITLE
Tracking issue to bump dependent rust crates prior to protocol 22

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#1353]
### What?
Audit our dependent crates to see if we need to bump their versions. Also, compare stellar-core pinned versions with that of rs-soroban-env crates.

### Why?
For example, we have curve25519-dalek crate in env that allows for the version range of 4.1.1 to 4.1.2 while core pins to 4.1.1. Evaluate to see if we can pin env to a specific version and point core to that.
```[tasklist]
### Tasks
- [ ] curve25519-dalek crate v4.1.2
- [ ] k256 v13.3.0
- [ ] Related issue, https://github.com/stellar/rs-soroban-env/issues/1422
- [ ] Another related issue, https://github.com/stellar/stellar-core/issues/4278
```

**Comment by anupsdf** [comment]
We can do this once https://github.com/stellar/stellar-core/issues/4278 if fixed.
