### ISSUE TITLE
A bunch of simple renamings

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#689]
This is a tracking issue for a bunch of simple renamings to do.

```[tasklist]
### Tasks
- [x] `Status` => `Error`
- [ ] `env_val.rs` => merge content into `convert.rs`
- [ ] `RawVal` => `Val`
- [ ] `RawValConvertable` => `ValConvert` (and possibly make crate-private)
-  [ ] `TryFromVal` `TryIntoVal` => `EnvConvertFrom` / `EnvConvertTo`
- [ ] `Convert` => `EnvConvert`
```

The last three I'm not as certain about, but I think it'd help (a) emphasize the interrelated-ness of the traits and (b) emphasize that what's called `Convert` today is always actually implemented by an `Env` and (c) remove one weird part of `TryFromVal` which is that it's often not converting _from_ a `RawVal` at all, it might even be converting _to_ a `RawVal` (eg. `impl TryFromVal<ScVal> for RawVal` which would I think read better `impl EnvConvertFrom<ScVal> for Val`

**Comment by graydon** [comment]
@leighmcculloch @paulbellamy @sisuresh @jayz22 @dmkozh during value overhaul we postponed a few renamings as "too systematic to bother with at the time and easy to do later" -- I'd be curious to hear your preferences on these names

**Comment by dmkozh** [comment]
I really like the idea of separating the `try_from_val` into 2 cases - the current state doesn't make much sense to me when we convert from env values to, say, `ScVal` (which is outside of env). As for the specific naming, I don't have a strong opinion. Given that `RawVal` is currently usable and useful in the SDK, maybe something like `AnyVal` could be a better fit. But `Val` seems ok to me as well.

**Comment by jayz22** [comment]
`Status` => `Error`, what do we do with `Status::OK` and how do we plan to handle status-returning host functions where the success or failure status is indicated by `Status`?  Will such functions just be `void`-returning where the status will be captured by the `HostError`?
`RawVal` => `Val`, I think this makes sense which resolves the confusion of `RawVal::from_u32(u: u32) -> U32Val`.
`TryFromVal`: One other choice of name proposed before was `TryFromViaEnv` which I also liked.

**Comment by graydon** [comment]
@dmkozh can you say a little more about "separating into two cases"? If you mean conversions that use the env vs. those that don't, the latter are already supported (where possible) through From/Into or TryFrom/TryInto.

**Comment by graydon** [comment]
@jayz22 `Status::OK` would go away and the cases that return it would become `void`-returning yes.

**Comment by dmkozh** [comment]
> @dmkozh can you say a little more about "separating into two cases"? If you mean conversions that use the env vs. those that don't, the latter are already supported (where possible) through From/Into or TryFrom/TryInto.

TBH I don't exactly remember what I was referring to there, probably just wanted to +1 the (c) part of the issue, but I realize now that it's not really two cases. So nothing special here, I'm in favor of the renaming.

**Comment by leighmcculloch** [comment]
Most look great, or inconsequential:

- `Status` => `Error` ✅ 💯 
- `env_val.rs` => merge content into `convert.rs` ✅ 🤷🏻 
- `RawVal` => `Val` ✅ 💯 
- `RawValConvertable` => `ValConvert` ✅ 🤷🏻 

Could we drop the `Env` prefixes for the conversion types? It's not clear what value it adds. Naming them something other than `TryFrom` / `TryInto`, as we'd be doing using the term `Convert`, should sufficiently set them apart as working a bit differently to the stdlib conversion traits so that we don't need to include terms like Val or Env in their name.

- `TryFromVal` `TryIntoVal` => `EnvConvertFrom` / `EnvConvertTo`
- `Convert` => `EnvConvert`

@graydon Do you think we could get rid of one of the From / To traits so that we only have one?

**Comment by graydon** [comment]
@leighmcculloch I don't think we can get rid of the other side of the From/To traits no; I tried it before and they both wind up used fairly often in idioms that are very clunky to write "the opposite way". I did the most I could do, and defined one in terms of a blanket on the other, so we should only ever _write_ `TryFromVal` impls, but `TryIntoVal` remains (or whatever we rename it to)

**Comment by graydon** [comment]
I think everything that was going to happen here has happened. CLosing.
