### ISSUE TITLE
Soroban launch criteria for Testnet release

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#971]
### Soroban launch criteria for Testnet

The tasks mentioned below will be our launch criteria to release Soroban in Testnet.
The [project board](https://github.com/orgs/stellar/projects/39/views/12) has list of issues with target milestones and priorities,
```
P0: Testnet blocking issue
P1: After Testnet but fixed for v20.0.0
P2: Can be fixed in a dot release, v20.x.y
```

The task lists are in order of priority and all of them need to be completed before we can go to Testnet.

```[tasklist]
### Dev complete ([Full list of Testnet P0 issues](https://github.com/orgs/stellar/projects/39/views/12?filterQuery=status%3ABacklog%2CUpNext%2C%22In+Progress%22+priority%3AP0+target-milestone%3A%22Testnet*%22))
- [x] State Expiration P0 issues
- [x] [Auth metering](https://github.com/stellar/rs-soroban-env/issues/668)
- [x] Expiration bump logic refactor
- [x] [Migrate to curve25519-dalek 4.0.0 rust library and ed25519v2.0.rc23](https://github.com/stellar/rs-soroban-env/issues/963)
- [x] [Network settings upgrade tool](https://github.com/stellar/stellar-core/pull/3843)
- [x] XDR branch next to curr
- [x] [Enable Soroban code in Core (IFDEF removal ](https://github.com/stellar/stellar-core/issues/3662)
- [x] [Enforce max expiration ledger](https://github.com/stellar/rs-soroban-env/issues/973)
```

```[tasklist]
### Getting ready for Testnet
- [x] Write new CAPs for State Expiration, Auth
- [x] Update existing CAPs
- [x] [Review CAPs and file issues](https://github.com/stellar/rs-soroban-env/issues/881)
- [ ] [Code review](https://github.com/stellar/rs-soroban-env/issues/881) of core and env. Check for test coverage, quality of tests.
- [ ] Write unit tests to bring [test coverage](https://htmlpreview.github.io/?https://github.com/anupsdf/testcoverage/blob/main/20230728/html/index.html) to 90+ %
```

```[tasklist]
### Pre-launch
- [ ] Create Core package
- [ ] Dry run in Futurenet along with Platform dependencies
```

**Comment by anupsdf** [comment]
Closing this as we decided to move to Testnet without the higher test coverage numbers as originally planned. We will add more tests before the v20 stable release.
